insert into Library (libraryID, libraryName, universityName, City, Address) values (1651961732, 'Community Library', 'Shawnee State University', 'Salavan', '1 Nobel Way');
insert into Library (libraryID, libraryName, universityName, City, Address) values (637226228, 'Central Library', 'Drzavni Univerzitet u Novom Pazaru', 'Knin', '541 Village Green Trail');
insert into Library (libraryID, libraryName, universityName, City, Address) values (969041659, 'City Library', 'Universidad Católica de Santiago de Guayaquil', 'Ar Ramāḑīn', '2629 Vidon Alley');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1804446712, 'Public Library', 'Kyushu Sangyo University', 'Nora', '8409 Randy Hill');
insert into Library (libraryID, libraryName, universityName, City, Address) values (424360900, 'Central Library', 'Curtin University of Technology', 'Dibba Al-Hisn', '7396 Duke Plaza');
insert into Library (libraryID, libraryName, universityName, City, Address) values (528554062, 'Central Library', 'National College of Ireland', 'Imotski', '469 Westridge Hill');
insert into Library (libraryID, libraryName, universityName, City, Address) values (259373026, 'Public Library', 'University of Science and Technology', 'Duluth', '53313 Daystar Circle');
insert into Library (libraryID, libraryName, universityName, City, Address) values (605821159, 'Community Library', 'Islamic Azad University, Hamedan', 'Lasehao', '48 Oxford Place');
insert into Library (libraryID, libraryName, universityName, City, Address) values (993395815, 'Public Library', 'Yeungnam University', 'Taihe', '969 Delladonna Avenue');
insert into Library (libraryID, libraryName, universityName, City, Address) values (683557459, 'Community Library', 'Oregon College of Arts and Crafts', 'Haramgai', '1 Prentice Way');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1235874590, 'City Library', 'Adventist University of the Philippines', 'Soio', '065 Dovetail Center');
insert into Library (libraryID, libraryName, universityName, City, Address) values (2066265047, 'Community Library', 'Rajiv Gandhi Technical University (University of Technology of Madhya Pradesh)', 'Wufeng', '680 Banding Lane');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1950770749, 'Community Library', 'Universidad Mexicana', 'Jimaguayú', '1851 Miller Court');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1300773186, 'Community Library', 'Catholic University of Malawi', 'Melville', '718 Buhler Plaza');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1273990051, 'Central Library', 'Tomas Bata University in Zlin', 'Estefania', '085 Hallows Parkway');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1656344750, 'Central Library', 'Zhezkazgan Baikonurov University', 'Ejidal', '97 Alpine Hill');
insert into Library (libraryID, libraryName, universityName, City, Address) values (102388246, 'National Library', 'Chukyo University', 'Tha Luang', '825 Fuller Plaza');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1548416003, 'National Library', 'University of Portharcourt', 'Guaratuba', '2200 Arkansas Place');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1586244507, 'National Library', 'University of Mkar', 'Kebonagung', '023 Bonner Drive');
insert into Library (libraryID, libraryName, universityName, City, Address) values (1040629489, 'Public Library', 'Morioka College', 'Georgiyevka', '7 Blue Bill Park Court');